version: '3.4'

services:
  rovema.api:
    image: ${DOCKER_REGISTRY-}rovemaapi
    container_name: rovema.api
    build:
      context: .
      dockerfile: Rovema.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  rovema.database:
    image: postgres:latest
    container_name: rovema.database
    environment:
      - POSTGRES_DB=rovemadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/rovemadb:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rovema.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'