version: '3.4'

services:
  rovema_api:
    image: ${DOCKER_REGISTRY-}rovemaapi
    container_name: rovema_api
    volumes:
      - rovemaapi_data:/var/lib/rovemaapi
    build:
      context: .
      dockerfile: Rovema.Api/Dockerfile
    ports:
      - "80:5000"
      - "443:5001"
    networks:
      - DcltNet
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_URL=redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=5cc3476ac2b3927a1438df59fac34936
      - POSTGRES_DATABASE=rovemadb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host('rovemaapi.dclt.com.br')
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000 
        - traefik.http.services.chatwoot_app.loadbalancer.passhostheader=true 
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader@docker

networks:
  DcltNet:
    external: true
    name: DcltNet

volumes:
  rovemaapi_data:
    external: true